-- MySQL Script generated by MySQL Workbench
-- Fri Mar  1 19:48:41 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema freelab
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `freelab` ;

-- -----------------------------------------------------
-- Schema freelab
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `freelab` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `freelab` ;

-- -----------------------------------------------------
-- Table `freelab`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freelab`.`roles` ;

CREATE TABLE IF NOT EXISTS `freelab`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `freelab`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freelab`.`users` ;

CREATE TABLE IF NOT EXISTS `freelab`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NULL DEFAULT NULL,
  `checked` TINYINT(1) NULL DEFAULT NULL,
  `idRole` INT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idRole` (`idRole` ASC) VISIBLE,
  CONSTRAINT `users_ibfk_1`
    FOREIGN KEY (`idRole`)
    REFERENCES `freelab`.`roles` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `freelab`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freelab`.`categories` ;

CREATE TABLE IF NOT EXISTS `freelab`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `freelab`.`freelancers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freelab`.`freelancers` ;

CREATE TABLE IF NOT EXISTS `freelab`.`freelancers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(255) NOT NULL,
  `lastName` VARCHAR(255) NOT NULL,
  `country` VARCHAR(255) NULL DEFAULT NULL,
  `phoneCode` INT NULL DEFAULT NULL,
  `phone` INT NULL DEFAULT NULL,
  `about` TEXT NULL DEFAULT NULL,
  `hourValue` INT NULL DEFAULT NULL,
  `idUser` INT NOT NULL,
  `idCategory` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idUser` (`idUser` ASC) VISIBLE,
  INDEX `idCategory` (`idCategory` ASC) VISIBLE,
  CONSTRAINT `freelancers_ibfk_1`
    FOREIGN KEY (`idUser`)
    REFERENCES `freelab`.`users` (`id`),
  CONSTRAINT `freelancers_ibfk_2`
    FOREIGN KEY (`idCategory`)
    REFERENCES `freelab`.`categories` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `freelab`.`states`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freelab`.`states` ;

CREATE TABLE IF NOT EXISTS `freelab`.`states` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `freelab`.`companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freelab`.`companies` ;

CREATE TABLE IF NOT EXISTS `freelab`.`companies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `companyName` VARCHAR(255) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `location` TEXT NULL DEFAULT NULL,
  `mainImage` TEXT NULL DEFAULT NULL,
  `website` TEXT NULL DEFAULT NULL,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idUser` (`idUser` ASC) VISIBLE,
  CONSTRAINT `companies_ibfk_1`
    FOREIGN KEY (`idUser`)
    REFERENCES `freelab`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `freelab`.`projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freelab`.`projects` ;

CREATE TABLE IF NOT EXISTS `freelab`.`projects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `idStatus` INT NULL DEFAULT NULL,
  `idCompany` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idStatus` (`idStatus` ASC) VISIBLE,
  INDEX `idCompany` (`idCompany` ASC) VISIBLE,
  CONSTRAINT `projects_ibfk_1`
    FOREIGN KEY (`idStatus`)
    REFERENCES `freelab`.`states` (`id`),
  CONSTRAINT `projects_ibfk_2`
    FOREIGN KEY (`idCompany`)
    REFERENCES `freelab`.`companies` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `freelab`.`individuals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freelab`.`individuals` ;

CREATE TABLE IF NOT EXISTS `freelab`.`individuals` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `specialty` VARCHAR(255) NULL DEFAULT NULL,
  `about` TEXT NULL DEFAULT NULL,
  `price` INT NULL DEFAULT NULL,
  `idProject` INT NOT NULL,
  `chosen` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idProject` (`idProject` ASC) VISIBLE,
  CONSTRAINT `individuals_ibfk_1`
    FOREIGN KEY (`idProject`)
    REFERENCES `freelab`.`projects` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `freelab`.`applications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freelab`.`applications` ;

CREATE TABLE IF NOT EXISTS `freelab`.`applications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idFreelancer` INT NOT NULL,
  `idIndividual` INT NULL DEFAULT NULL,
  `selected` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idFreelancer` (`idFreelancer` ASC) VISIBLE,
  INDEX `idIndividual` (`idIndividual` ASC) VISIBLE,
  CONSTRAINT `applications_ibfk_1`
    FOREIGN KEY (`idFreelancer`)
    REFERENCES `freelab`.`freelancers` (`id`),
  CONSTRAINT `applications_ibfk_2`
    FOREIGN KEY (`idIndividual`)
    REFERENCES `freelab`.`individuals` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `freelab`.`favorites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freelab`.`favorites` ;

CREATE TABLE IF NOT EXISTS `freelab`.`favorites` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idFreelancer` INT NOT NULL,
  `idProject` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idFreelancer` (`idFreelancer` ASC) VISIBLE,
  INDEX `idProject` (`idProject` ASC) VISIBLE,
  CONSTRAINT `favorites_ibfk_1`
    FOREIGN KEY (`idFreelancer`)
    REFERENCES `freelab`.`freelancers` (`id`),
  CONSTRAINT `favorites_ibfk_2`
    FOREIGN KEY (`idProject`)
    REFERENCES `freelab`.`projects` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `freelab`.`skilles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freelab`.`skilles` ;

CREATE TABLE IF NOT EXISTS `freelab`.`skilles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `shape` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 71
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `freelab`.`freelancerskills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freelab`.`freelancerskills` ;

CREATE TABLE IF NOT EXISTS `freelab`.`freelancerskills` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idFreelancer` INT NULL DEFAULT NULL,
  `idSkill` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idFreelancer` (`idFreelancer` ASC) VISIBLE,
  INDEX `idSkill` (`idSkill` ASC) VISIBLE,
  CONSTRAINT `freelancerskills_ibfk_1`
    FOREIGN KEY (`idFreelancer`)
    REFERENCES `freelab`.`freelancers` (`id`),
  CONSTRAINT `freelancerskills_ibfk_2`
    FOREIGN KEY (`idSkill`)
    REFERENCES `freelab`.`skilles` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `freelab`.`individualskills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freelab`.`individualskills` ;

CREATE TABLE IF NOT EXISTS `freelab`.`individualskills` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idIndividual` INT NULL DEFAULT NULL,
  `idSkill` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idIndividual` (`idIndividual` ASC) VISIBLE,
  INDEX `idSkill` (`idSkill` ASC) VISIBLE,
  CONSTRAINT `individualskills_ibfk_1`
    FOREIGN KEY (`idIndividual`)
    REFERENCES `freelab`.`individuals` (`id`),
  CONSTRAINT `individualskills_ibfk_2`
    FOREIGN KEY (`idSkill`)
    REFERENCES `freelab`.`skilles` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `freelab`.`projectcategories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freelab`.`projectcategories` ;

CREATE TABLE IF NOT EXISTS `freelab`.`projectcategories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idProject` INT NULL DEFAULT NULL,
  `idCategory` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idProject` (`idProject` ASC) VISIBLE,
  INDEX `idCategory` (`idCategory` ASC) VISIBLE,
  CONSTRAINT `projectcategories_ibfk_1`
    FOREIGN KEY (`idProject`)
    REFERENCES `freelab`.`projects` (`id`),
  CONSTRAINT `projectcategories_ibfk_2`
    FOREIGN KEY (`idCategory`)
    REFERENCES `freelab`.`categories` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `freelab`.`projectskills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freelab`.`projectskills` ;

CREATE TABLE IF NOT EXISTS `freelab`.`projectskills` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idProject` INT NULL DEFAULT NULL,
  `idSkill` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idProject` (`idProject` ASC) VISIBLE,
  INDEX `idSkill` (`idSkill` ASC) VISIBLE,
  CONSTRAINT `projectskills_ibfk_1`
    FOREIGN KEY (`idProject`)
    REFERENCES `freelab`.`projects` (`id`),
  CONSTRAINT `projectskills_ibfk_2`
    FOREIGN KEY (`idSkill`)
    REFERENCES `freelab`.`skilles` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `freelab`.`reviews`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freelab`.`reviews` ;

CREATE TABLE IF NOT EXISTS `freelab`.`reviews` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idSender` INT NOT NULL,
  `idReceiver` INT NOT NULL,
  `score` INT NOT NULL,
  `comment` TEXT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idSender` (`idSender` ASC) VISIBLE,
  INDEX `idReceiver` (`idReceiver` ASC) VISIBLE,
  CONSTRAINT `reviews_ibfk_1`
    FOREIGN KEY (`idSender`)
    REFERENCES `freelab`.`users` (`id`),
  CONSTRAINT `reviews_ibfk_2`
    FOREIGN KEY (`idReceiver`)
    REFERENCES `freelab`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `freelab`.`sequelizemeta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freelab`.`sequelizemeta` ;

CREATE TABLE IF NOT EXISTS `freelab`.`sequelizemeta` (
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
