-- MySQL Script generated by MySQL Workbench
-- Thu Feb 22 23:37:04 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema FreeLab
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `FreeLab` ;

-- -----------------------------------------------------
-- Schema FreeLab
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FreeLab` DEFAULT CHARACTER SET utf8 ;
USE `FreeLab` ;

-- -----------------------------------------------------
-- Table `FreeLab`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeLab`.`categories` ;

CREATE TABLE IF NOT EXISTS `FreeLab`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`category_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeLab`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeLab`.`roles` ;

CREATE TABLE IF NOT EXISTS `FreeLab`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeLab`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeLab`.`users` ;

CREATE TABLE IF NOT EXISTS `FreeLab`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NULL,
  `checked` TINYINT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_roles_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_roles`
    FOREIGN KEY (`role_id`)
    REFERENCES `FreeLab`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeLab`.`freelancers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeLab`.`freelancers` ;

CREATE TABLE IF NOT EXISTS `FreeLab`.`freelancers` (
  `id` INT NOT NULL,
  `first_name` VARCHAR(65) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NULL,
  `phone_code` INT NULL,
  `phone` INT NULL,
  `about` TEXT NULL,
  `hour_value` INT NULL,
  `user_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_freelances_users_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_freelances_catgories_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_freelancers_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `FreeLab`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_freelancers_categories`
    FOREIGN KEY (`category_id`)
    REFERENCES `FreeLab`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeLab`.`status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeLab`.`status` ;

CREATE TABLE IF NOT EXISTS `FreeLab`.`status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeLab`.`companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeLab`.`companies` ;

CREATE TABLE IF NOT EXISTS `FreeLab`.`companies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_name` VARCHAR(100) NOT NULL,
  `description` TEXT NOT NULL,
  `location` TEXT NULL,
  `main_image` TEXT NULL,
  `website` TEXT NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_companies_users_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_companies_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `FreeLab`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeLab`.`projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeLab`.`projects` ;

CREATE TABLE IF NOT EXISTS `FreeLab`.`projects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `description` TEXT NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NULL,
  `status_id` INT NOT NULL,
  `company_id` INT NOT NULL,
  `price` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_publication_status_idx` (`status_id` ASC) VISIBLE,
  INDEX `fk_publication_company_idx` (`company_id` ASC) VISIBLE,
  CONSTRAINT `fk_projects_status`
    FOREIGN KEY (`status_id`)
    REFERENCES `FreeLab`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projects_company`
    FOREIGN KEY (`company_id`)
    REFERENCES `FreeLab`.`companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeLab`.`favorites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeLab`.`favorites` ;

CREATE TABLE IF NOT EXISTS `FreeLab`.`favorites` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_freelancer` INT NOT NULL,
  `id_project` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_favorite_freelancer_idx` (`id_freelancer` ASC) VISIBLE,
  INDEX `fk_favorite_publication_idx` (`id_project` ASC) VISIBLE,
  CONSTRAINT `fk_favorite_freelancer`
    FOREIGN KEY (`id_freelancer`)
    REFERENCES `FreeLab`.`freelancers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favorite_publication`
    FOREIGN KEY (`id_project`)
    REFERENCES `FreeLab`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeLab`.`skilles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeLab`.`skilles` ;

CREATE TABLE IF NOT EXISTS `FreeLab`.`skilles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `shape` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeLab`.`reviewes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeLab`.`reviewes` ;

CREATE TABLE IF NOT EXISTS `FreeLab`.`reviewes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sender_id` INT NOT NULL,
  `receiver_id` INT NOT NULL,
  `score` INT NOT NULL,
  `comment` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_review_sender_idx` (`sender_id` ASC) VISIBLE,
  INDEX `fk_review_receiver_idx` (`receiver_id` ASC) VISIBLE,
  CONSTRAINT `fk_review_sender`
    FOREIGN KEY (`sender_id`)
    REFERENCES `FreeLab`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_review_receiver`
    FOREIGN KEY (`receiver_id`)
    REFERENCES `FreeLab`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeLab`.`freelancer_skill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeLab`.`freelancer_skill` ;

CREATE TABLE IF NOT EXISTS `FreeLab`.`freelancer_skill` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `freelancer_id` INT NOT NULL,
  `skill_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_freelancer_skill_idx` (`freelancer_id` ASC) VISIBLE,
  INDEX `fk_skill_freelancer_idx` (`skill_id` ASC) VISIBLE,
  CONSTRAINT `fk_freelancer_skill`
    FOREIGN KEY (`freelancer_id`)
    REFERENCES `FreeLab`.`freelancers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_skill_freelancer`
    FOREIGN KEY (`skill_id`)
    REFERENCES `FreeLab`.`skilles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeLab`.`projects_skill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeLab`.`projects_skill` ;

CREATE TABLE IF NOT EXISTS `FreeLab`.`projects_skill` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `project_id` INT NOT NULL,
  `skill_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_skill_freelancer_idx` (`skill_id` ASC) VISIBLE,
  INDEX `fk_publication_skill_idx` (`project_id` ASC) VISIBLE,
  CONSTRAINT `fk_project_skill`
    FOREIGN KEY (`project_id`)
    REFERENCES `FreeLab`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_skill_project`
    FOREIGN KEY (`skill_id`)
    REFERENCES `FreeLab`.`skilles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeLab`.`projects_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeLab`.`projects_category` ;

CREATE TABLE IF NOT EXISTS `FreeLab`.`projects_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `projects_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_publication_category_idx` (`projects_id` ASC) VISIBLE,
  INDEX `fk_category_publication_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_projects_category`
    FOREIGN KEY (`projects_id`)
    REFERENCES `FreeLab`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_category_projects`
    FOREIGN KEY (`category_id`)
    REFERENCES `FreeLab`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeLab`.`individuals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeLab`.`individuals` ;

CREATE TABLE IF NOT EXISTS `FreeLab`.`individuals` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `specialty` VARCHAR(100) NOT NULL,
  `skills_id` INT NOT NULL,
  `about` TEXT NULL,
  `price` INT NOT NULL,
  `projects_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_individual_project_idx` (`projects_id` ASC) VISIBLE,
  CONSTRAINT `fk_individual_project`
    FOREIGN KEY (`projects_id`)
    REFERENCES `FreeLab`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeLab`.`applications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeLab`.`applications` ;

CREATE TABLE IF NOT EXISTS `FreeLab`.`applications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_freelancer` INT NOT NULL,
  `id_individuals` INT NOT NULL,
  INDEX `fk_freelancer_individuals_idx` (`id_freelancer` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `fk_individuals_freelancer_idx` (`id_individuals` ASC) VISIBLE,
  CONSTRAINT `fk_freelancer_individuals`
    FOREIGN KEY (`id_freelancer`)
    REFERENCES `FreeLab`.`freelancers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_individuals_freelancer`
    FOREIGN KEY (`id_individuals`)
    REFERENCES `FreeLab`.`individuals` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeLab`.`individual_skill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeLab`.`individual_skill` ;

CREATE TABLE IF NOT EXISTS `FreeLab`.`individual_skill` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `individual_id` INT NOT NULL,
  `skill_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_individual_skill_idx` (`individual_id` ASC) VISIBLE,
  INDEX `fk_skill_individual_idx` (`skill_id` ASC) VISIBLE,
  CONSTRAINT `fk_individual_skill`
    FOREIGN KEY (`individual_id`)
    REFERENCES `FreeLab`.`individuals` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_skill_individual`
    FOREIGN KEY (`skill_id`)
    REFERENCES `FreeLab`.`skilles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `FreeLab` ;

-- -----------------------------------------------------
-- Placeholder table for view `FreeLab`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FreeLab`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `FreeLab`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeLab`.`view1`;
DROP VIEW IF EXISTS `FreeLab`.`view1` ;
USE `FreeLab`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
