-- MySQL Script generated by MySQL Workbench
-- Sun Feb 25 00:33:44 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema FreeLab
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `FreeLab` ;

-- -----------------------------------------------------
-- Schema FreeLab
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FreeLab` DEFAULT CHARACTER SET utf8 ;
USE `FreeLab` ;

-- -----------------------------------------------------
-- Table `FreeLab`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeLab`.`categories` ;

CREATE TABLE IF NOT EXISTS `FreeLab`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeLab`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeLab`.`roles` ;

CREATE TABLE IF NOT EXISTS `FreeLab`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeLab`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeLab`.`users` ;

CREATE TABLE IF NOT EXISTS `FreeLab`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NULL,
  `checked` TINYINT NULL DEFAULT 0,
  `idRole` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_roles_idx` (`idRole` ASC) VISIBLE,
  CONSTRAINT `fk_users_roles`
    FOREIGN KEY (`idRole`)
    REFERENCES `FreeLab`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeLab`.`freelancers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeLab`.`freelancers` ;

CREATE TABLE IF NOT EXISTS `FreeLab`.`freelancers` (
  `id` INT NOT NULL,
  `firstName` VARCHAR(65) NOT NULL,
  `lastName` VARCHAR(65) NOT NULL,
  `country` VARCHAR(45) NULL,
  `phoneCode` INT NULL,
  `phone` INT NULL,
  `about` TEXT NULL,
  `hourValue` INT NULL,
  `idUser` INT NOT NULL,
  `idCategory` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_freelances_users_idx` (`idUser` ASC) VISIBLE,
  INDEX `fk_freelances_catgories_idx` (`idCategory` ASC) VISIBLE,
  CONSTRAINT `fk_freelancers_users`
    FOREIGN KEY (`idUser`)
    REFERENCES `FreeLab`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_freelancers_categories`
    FOREIGN KEY (`idCategory`)
    REFERENCES `FreeLab`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeLab`.`status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeLab`.`status` ;

CREATE TABLE IF NOT EXISTS `FreeLab`.`status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeLab`.`companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeLab`.`companies` ;

CREATE TABLE IF NOT EXISTS `FreeLab`.`companies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `companyName` VARCHAR(100) NOT NULL,
  `description` TEXT NOT NULL,
  `location` TEXT NULL,
  `mainImage` TEXT NULL,
  `website` TEXT NULL,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_companies_users_idx` (`idUser` ASC) VISIBLE,
  CONSTRAINT `fk_companies_users`
    FOREIGN KEY (`idUser`)
    REFERENCES `FreeLab`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeLab`.`projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeLab`.`projects` ;

CREATE TABLE IF NOT EXISTS `FreeLab`.`projects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `description` TEXT NOT NULL,
  `createdAt` DATE NOT NULL,
  `updatedAt` DATE NULL,
  `idStatus` INT NOT NULL,
  `idCompany` INT NOT NULL,
  `price` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_publication_status_idx` (`idStatus` ASC) VISIBLE,
  INDEX `fk_publication_company_idx` (`idCompany` ASC) VISIBLE,
  CONSTRAINT `fk_projects_status`
    FOREIGN KEY (`idStatus`)
    REFERENCES `FreeLab`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projects_company`
    FOREIGN KEY (`idCompany`)
    REFERENCES `FreeLab`.`companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeLab`.`favorites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeLab`.`favorites` ;

CREATE TABLE IF NOT EXISTS `FreeLab`.`favorites` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idFreelancer` INT NOT NULL,
  `idProject` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_favorite_freelancer_idx` (`idFreelancer` ASC) VISIBLE,
  INDEX `fk_favorite_publication_idx` (`idProject` ASC) VISIBLE,
  CONSTRAINT `fk_favorite_freelancer`
    FOREIGN KEY (`idFreelancer`)
    REFERENCES `FreeLab`.`freelancers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favorite_publication`
    FOREIGN KEY (`idProject`)
    REFERENCES `FreeLab`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeLab`.`skilles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeLab`.`skilles` ;

CREATE TABLE IF NOT EXISTS `FreeLab`.`skilles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `shape` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeLab`.`reviewes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeLab`.`reviewes` ;

CREATE TABLE IF NOT EXISTS `FreeLab`.`reviewes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idSender` INT NOT NULL,
  `idReceiver` INT NOT NULL,
  `score` INT NOT NULL,
  `comment` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_review_sender_idx` (`idSender` ASC) VISIBLE,
  INDEX `fk_review_receiver_idx` (`idReceiver` ASC) VISIBLE,
  CONSTRAINT `fk_review_sender`
    FOREIGN KEY (`idSender`)
    REFERENCES `FreeLab`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_review_receiver`
    FOREIGN KEY (`idReceiver`)
    REFERENCES `FreeLab`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeLab`.`freelancer_skill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeLab`.`freelancer_skill` ;

CREATE TABLE IF NOT EXISTS `FreeLab`.`freelancer_skill` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idFreelancer` INT NOT NULL,
  `idSkill` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_freelancer_skill_idx` (`idFreelancer` ASC) VISIBLE,
  INDEX `fk_skill_freelancer_idx` (`idSkill` ASC) VISIBLE,
  CONSTRAINT `fk_freelancer_skill`
    FOREIGN KEY (`idFreelancer`)
    REFERENCES `FreeLab`.`freelancers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_skill_freelancer`
    FOREIGN KEY (`idSkill`)
    REFERENCES `FreeLab`.`skilles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeLab`.`projects_skill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeLab`.`projects_skill` ;

CREATE TABLE IF NOT EXISTS `FreeLab`.`projects_skill` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idProject` INT NOT NULL,
  `idSkill` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_skill_freelancer_idx` (`idSkill` ASC) VISIBLE,
  INDEX `fk_publication_skill_idx` (`idProject` ASC) VISIBLE,
  CONSTRAINT `fk_project_skill`
    FOREIGN KEY (`idProject`)
    REFERENCES `FreeLab`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_skill_project`
    FOREIGN KEY (`idSkill`)
    REFERENCES `FreeLab`.`skilles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeLab`.`projects_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeLab`.`projects_category` ;

CREATE TABLE IF NOT EXISTS `FreeLab`.`projects_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idProject` INT NOT NULL,
  `idCategory` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_publication_category_idx` (`idProject` ASC) VISIBLE,
  INDEX `fk_category_publication_idx` (`idCategory` ASC) VISIBLE,
  CONSTRAINT `fk_projects_category`
    FOREIGN KEY (`idProject`)
    REFERENCES `FreeLab`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_category_projects`
    FOREIGN KEY (`idCategory`)
    REFERENCES `FreeLab`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeLab`.`individuals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeLab`.`individuals` ;

CREATE TABLE IF NOT EXISTS `FreeLab`.`individuals` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `specialty` VARCHAR(100) NOT NULL,
  `about` TEXT NULL,
  `price` INT NOT NULL,
  `idProject` INT NOT NULL,
  `chosen` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_individual_project_idx` (`idProject` ASC) VISIBLE,
  CONSTRAINT `fk_individual_project`
    FOREIGN KEY (`idProject`)
    REFERENCES `FreeLab`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeLab`.`applications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeLab`.`applications` ;

CREATE TABLE IF NOT EXISTS `FreeLab`.`applications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idFreelancer` INT NOT NULL,
  `idIndividual` INT NOT NULL,
  `selected` TINYINT NOT NULL DEFAULT 0,
  INDEX `fk_freelancer_individuals_idx` (`idFreelancer` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `fk_individuals_freelancer_idx` (`idIndividual` ASC) VISIBLE,
  CONSTRAINT `fk_freelancer_individuals`
    FOREIGN KEY (`idFreelancer`)
    REFERENCES `FreeLab`.`freelancers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_individual_freelancer`
    FOREIGN KEY (`idIndividual`)
    REFERENCES `FreeLab`.`individuals` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeLab`.`individual_skill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeLab`.`individual_skill` ;

CREATE TABLE IF NOT EXISTS `FreeLab`.`individual_skill` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idIndividual` INT NOT NULL,
  `idSkill` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_individual_skill_idx` (`idIndividual` ASC) VISIBLE,
  INDEX `fk_skill_individual_idx` (`idSkill` ASC) VISIBLE,
  CONSTRAINT `fk_individual_skill`
    FOREIGN KEY (`idIndividual`)
    REFERENCES `FreeLab`.`individuals` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_skill_individual`
    FOREIGN KEY (`idSkill`)
    REFERENCES `FreeLab`.`skilles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
