-- MySQL Script generated by MySQL Workbench
-- Thu Feb 22 14:32:11 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema FreeLab
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema FreeLab
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FreeLab` DEFAULT CHARACTER SET utf8 ;
USE `FreeLab` ;

-- -----------------------------------------------------
-- Table `FreeLab`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FreeLab`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`category_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeLab`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FreeLab`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeLab`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FreeLab`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NULL,
  `checked` TINYINT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_roles_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_roles`
    FOREIGN KEY (`role_id`)
    REFERENCES `FreeLab`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeLab`.`freelancers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FreeLab`.`freelancers` (
  `id` INT NOT NULL,
  `first_name` VARCHAR(65) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NULL,
  `phone_code` INT NULL,
  `phone` INT NULL,
  `about` VARCHAR(45) NULL,
  `hour_value` INT NULL,
  `user_id` INT NULL,
  `category_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_freelances_users_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_freelances_catgorieidids_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_freelancers_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `FreeLab`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_freelancers_categories`
    FOREIGN KEY (`category_id`)
    REFERENCES `FreeLab`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeLab`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FreeLab`.`status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeLab`.`companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FreeLab`.`companies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_name` VARCHAR(100) NOT NULL,
  `description` TEXT NOT NULL,
  `location` TEXT NULL,
  `main_image` TEXT NULL,
  `website` TEXT NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_companies_users_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_companies_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `FreeLab`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeLab`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FreeLab`.`projects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `description` TEXT NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NULL,
  `status_id` INT NOT NULL,
  `company_id` INT NOT NULL,
  `quantity` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_publication_status_idx` (`status_id` ASC) VISIBLE,
  INDEX `fk_publication_company_idx` (`company_id` ASC) VISIBLE,
  CONSTRAINT `fk_projects_status`
    FOREIGN KEY (`status_id`)
    REFERENCES `FreeLab`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projects_company`
    FOREIGN KEY (`company_id`)
    REFERENCES `FreeLab`.`companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeLab`.`favorites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FreeLab`.`favorites` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_freelancer` INT NOT NULL,
  `id_projects` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_favorite_freelancer_idx` (`id_freelancer` ASC) VISIBLE,
  INDEX `fk_favorite_publication_idx` (`id_projects` ASC) VISIBLE,
  CONSTRAINT `fk_favorite_freelancer`
    FOREIGN KEY (`id_freelancer`)
    REFERENCES `FreeLab`.`freelancers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favorite_publication`
    FOREIGN KEY (`id_projects`)
    REFERENCES `FreeLab`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeLab`.`skilles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FreeLab`.`skilles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `image` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeLab`.`reviewes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FreeLab`.`reviewes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_company` INT NOT NULL,
  `score` INT NOT NULL,
  `comment` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_review_freelancer_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_review_company_idx` (`id_company` ASC) VISIBLE,
  CONSTRAINT `fk_review_freelancer`
    FOREIGN KEY (`id_user`)
    REFERENCES `FreeLab`.`freelancers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_review_company`
    FOREIGN KEY (`id_company`)
    REFERENCES `FreeLab`.`companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeLab`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FreeLab`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeLab`.`freelancer_skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FreeLab`.`freelancer_skill` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `freelancer_id` INT NOT NULL,
  `skill_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_freelancer_skill_idx` (`freelancer_id` ASC) VISIBLE,
  INDEX `fk_skill_freelancer_idx` (`skill_id` ASC) VISIBLE,
  CONSTRAINT `fk_freelancer_skill`
    FOREIGN KEY (`freelancer_id`)
    REFERENCES `FreeLab`.`freelancers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_skill_freelancer`
    FOREIGN KEY (`skill_id`)
    REFERENCES `FreeLab`.`skilles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeLab`.`projects_skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FreeLab`.`projects_skill` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `projects_id` INT NOT NULL,
  `skill_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_skill_freelancer_idx` (`skill_id` ASC) VISIBLE,
  INDEX `fk_publication_skill_idx` (`projects_id` ASC) VISIBLE,
  CONSTRAINT `fk_publication_skill`
    FOREIGN KEY (`projects_id`)
    REFERENCES `FreeLab`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_skill_publiaction`
    FOREIGN KEY (`skill_id`)
    REFERENCES `FreeLab`.`skilles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeLab`.`projects_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FreeLab`.`projects_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `projects_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  `hour_value` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_publication_category_idx` (`projects_id` ASC) VISIBLE,
  INDEX `fk_category_publication_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_publication_category`
    FOREIGN KEY (`projects_id`)
    REFERENCES `FreeLab`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_category_publication`
    FOREIGN KEY (`category_id`)
    REFERENCES `FreeLab`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FreeLab`.`applications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FreeLab`.`applications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_projects` INT NOT NULL,
  `score` INT NOT NULL,
  `comment` VARCHAR(255) NOT NULL,
  INDEX `fk_review_freelancer_idx` (`id_user` ASC, `id_projects` ASC) VISIBLE,
  INDEX `fk_review_company_idx` (`id_projects` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_review_freelancer0`
    FOREIGN KEY (`id_user` , `id_projects`)
    REFERENCES `FreeLab`.`freelancers` (`id` , `id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_review_company0`
    FOREIGN KEY (`id_projects`)
    REFERENCES `FreeLab`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `FreeLab` ;

-- -----------------------------------------------------
-- Placeholder table for view `FreeLab`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FreeLab`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `FreeLab`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FreeLab`.`view1`;
USE `FreeLab`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
